on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    # name: Snowsql Test
    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v2
    #     with:
    #       fetch-depth: 0

    #   - name: Setup NodeJS 14
    #     uses: actions/setup-node@v1
    #     with:
    #       node-version: 14
    steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4
        with:
          repository: ${{ github.repository }}
          token: ${{ github.token }}
      - name: Install npm
        run: |
          sudo apt-get update \
          && sudo apt-get install -y curl \
          && curl -sL https://deb.nodesource.com/setup_14.x | bash - \
          && sudo apt-get install -y nodejs \
          &&  scurl -L https://www.npmjs.com/install.sh | sh
      - name: install snowsql tool
        run: |
          npm install snowsql-formatter-cli -g
      - name: Testing
        uses: evarevear/snowsql-formatter-action@main
      - name: WHY
        run: echo "woooork"
      # Checkout the source code so we have some files to look at.
      # - name: Checkout
      #   uses: actions/checkout@v2
      #   with:
      #     fetch-depth: 0
      # Run the reformat action
      # - name: Reformat SQL Files
      #   uses: evarevear/snowsql-formatter-action@master